#############################################################################
# Generic Linux Makefile for SIMLIB test models
# the goal is test basic SIMLIB functionality

# we expect SIMLIB installed in parent subdirectory
SIMLIB_DIR = ../src

CXXFLAGS += -I$(SIMLIB_DIR)

# depends on shared library and all SIMLIB headers
SIMLIB_DEPEND = $(SIMLIB_DIR)/simlib.h \
		$(SIMLIB_DIR)/delay.h \
		$(SIMLIB_DIR)/zdelay.h \
		$(SIMLIB_DIR)/simlib2D.h \
		$(SIMLIB_DIR)/simlib3D.h \
		$(SIMLIB_DIR)/simlib.so 

# Implicit Rule to compile test models
% : %.cc  $(SIMLIB_DEPEND)
	$(CXX) $(CXXFLAGS) -o $@  $< $(SIMLIB_DIR)/simlib.so -lm

# list of all test models
ALL_TEST_MODELS =       \
	3d-test         \
	barrier-test1 \
	barrier-test2 \
	delay-test      \
	delay-test2     \
	zdelay-test     \
	waituntil-test  \
	process-test    \
	sizeof-all      \
	random-test     \
	test1           \
	test2           \
	test3           \
	test4           \
	test5           \
        test-calendar \
        test-reactivate

#############################################################################
# RULES

all: $(ALL_TEST_MODELS)

run: all
	@for i in $(ALL_TEST_MODELS); do echo $$i; ./$$i >$$i.out; done
	@./sizeof-all >sizeof-all-`file ./sizeof-all|sed 's/.*\([36][24]\)-bit.*/\1/'`.out

#############################################################################
# cleaning, backup, etc

clean: 
	rm -f $(ALL_TEST_MODELS) *.o *~

clean-all: clean
	rm -f *.dat *.out

pack:
	tar czf tests.tar.gz  *.cc Makefile* *.txt *.output *.plt

# end of Makefile
